# Generated by Django 5.0.6 on 2026-06-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('IN', 'Receipt'), ('OUT', 'Write-off'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('INVENTORY', 'Inventory correction')], max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
