# Generated by Django 5.0.6 on 2026-06-05 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivery_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel', 'sent_at'], name='notificatio_channel_3c710d_idx'),
        ),
    ]
