# Generated by Django 5.0.6 on 2026-06-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='customer_phone',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='telegram_username',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='aiwebhooklog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System'), ('STAFF', 'Staff')], max_length=32),
        ),
    ]
