# Generated by Django 5.0.6 on 2026-06-04 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clientprofile_external_ai_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in Kyrgyz format: +996123123123.', regex='^\\+996\\d{9}$')]),
        ),
    ]
