# Generated by Django 5.0.6 on 2026-06-04 18:59

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='external_ai_id',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='complaints',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='contraindications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='current_routine',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='previous_treatments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='skin_concerns',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='skin_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in Kyrgyz format: +996123123123.', regex='^\\+996\\d{9}$')]),
        ),
    ]
