# Generated by Django 5.0.6 on 2026-06-05 06:16

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_clientprofile_external_ai_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in Kyrgyz format: +996123123123.', regex='^\\+996\\d{9}$')])),
                ('code_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login')], default='LOGIN', max_length=32)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'indexes': [models.Index(fields=['phone', 'purpose', 'consumed_at'], name='users_phone_phone_e5d725_idx'), models.Index(fields=['expires_at'], name='users_phone_expires_1cfecb_idx')],
            },
        ),
    ]
