# Generated by Django 5.0.6 on 2026-06-04 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bonustransaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='bonus_transaction_amount_positive'),
        ),
    ]
