# Generated by Django 5.0.6 on 2026-06-04 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_batch_stockmovement_variant_and_more'),
        ('orders', '0002_initial'),
        ('products', '0003_alter_product_cost_price_alter_product_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productbatch'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productvariant'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('PACKING', 'Packing'), ('DELIVERING', 'Delivering'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=32)),
                ('to_status', models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('PACKING', 'Packing'), ('DELIVERING', 'Delivering'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_1de1d7_idx'), models.Index(fields=['to_status'], name='orders_orde_to_stat_047c71_idx')],
            },
        ),
    ]
